apiVersion: v1
kind: Service
metadata:
  name: backendservice
  labels:
    app: backendservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myappbackend