apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_frontend
  labels:
    app: deployment_frontend
spec:
  replicas: 5
  template:
    metadata:
      name: myappfrontend
      labels:
        app: myappfrontend
        tier: frontend
    spec:
      containers:
        - name: backend
          image: httpd
  selector:
    matchLabels:
      app: myappfrontend
    
