apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_backend
  labels:
    app: deployment_backend
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackend
      labels:
        app: myappbackend
        tier: backend
    spec:
      containers:
        - name: backend
          image: okteto/sample-app
  selector:
    matchLabels:
      app: myappbackend
    
