apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    app: myapp
    