apiVersion: apps/v1
kind: Deployment
metadata:
  name: depbackend
  labels:
    app: depbackend
spec:
  replicas: 5
  template:
    metadata:
      name: depbackend
      labels:
        app: myapp
        tier: backend
    spec:
      containers:
        - name: backend
          image: flask
  selector:
    matchLabels:
      app: backend
