apiVersion: apps/v1
kind: Deployment
metadata:
  name: depfrontend
  labels:
    app: depfrontend
spec:
  replicas: 5
  template:
    metadata:
      name: depfrontend
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: httpd
  selector:
    matchLabels:
      app: frontend
