# Özlem
# 1. Daha önce oluşturduğumuz deployment içinde pod içinde container olarak nginx kullandığımızdan emin olalım

# Özlem

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: deployment1
#   labels:
#     app: myappdep
# spec:
#   replicas: 30
#   template:
#     metadata:
#       name: myappbackend
#       labels:
#         app: myapp
#     spec:
#       containers:
#         - name: backend
#           image: nginx
#   selector:
#     matchLabels:
#       app: myapp
    

# 2. deployment dosyasını çalıştırmak için gereken kodu açıklama satırı şeklinde yazalım
     #kubectl create -f Egzersizler/Özlem/Özlem_deployment.yaml
  
# 3. bir node port üretelim service kullanarak

apiVersion: v1
kind: Service
metadata:
  name: ozlemNodePort
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    app: myapp
    
# 4. bu servisi mevcut deployment'a bağlayalım 

# 5. ardından bu servisin liste üzerinden doğrulamasını yapacak kodu yazalım  (k)
# kubectl get svc
# 6. servisi test edecek kodu yazalım 
  #minikube service ozlemNodePort


