Özlem
apiVersion: v1
kind: ReplicationController
metadata: 
  name: ornekreplicationcontroller
  labels:
    app: innova_app
spec:
  replicas: 5
  template:
    metadata:
      name: selam1
      labels: 
        app: selam
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: httpd
