# Özlem
# 1. Size ait içinde username,password ve ip bilgilerini tutan bir secret hazırlayınız
# 2. bu secrete kendi deployment dosyanız içerisine volumemount yöntemini kullanarak ekleyiniz. 

#   username: aW5ub3ZhCg== # innova
#   password: dW54a3ViZXJuZXRlcwo=  # unxkubernetes
#   ipAdres: MTAuMjAuMzMuMTQ4Cg== # 10.20.33.148


## Secret :

# apiVersion: v1
# kind: Secret
# metadata:
#   name: ozlemsecretname
# type: Opaque
# data:
#   username: aW5ub3ZhCg== 
#   password: dW54a3ViZXJuZXRlcwo= 
#   ip : MTAuMjAuMzMuMTQ4Cg==

## Deployment :

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozlemsecretdep
  labels:
    app: ozlemsecretdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depsecretozlem
  template:
    metadata:
      labels:
        app: depsecretozlem
    spec:
      containers:
        - name: dep-secret-volumes
          image: nginx
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/creds
              readOnly: true
      volumes: 
        - name: secret-volume
          secret:
            secretName: ozlemsecretname
              
