# Özlem

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: myappdep
spec:
  replicas: 30
  template:
    metadata:
      name: myappbackend
      labels:
        app: myapp
    spec:
      containers:
        - name: backend
          image: httpd:2.4.54-bullseye
  selector:
    matchLabels:
      app: myapp
    
