# Özlem
# 1. nginx imajına sahip bir containerın yer aldığı 5 replicası olan etiketi myappbackend olan bir deployment oluşturalım
# 2. bu deployment içerisinde liveness ve readiness probları yazalım. 
#     a. liveness probe için periyodikZaman=>20 initialDelaySecond => 30 timeout => 20
#     b. readiness probe için initialDelaySecond => 30 timeout => 40
# 3. her iki probe için bir port alias üzerinden işlem yapalım port alias için innovanodejs-port yazalım

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentOzlem
  labels:
    app: myappbackend
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackendOzlem
      labels:
        app: myappbackend
    spec:
      containers:
        - name: backend
          image: nginx
          ports:
          - name: innovanodejs-port
            containerPort: 3000
          livenessProbe:
            httpGet:
              path:  /health
              port: innovanodejs-port
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 40
          readinessProbe:
            httpGet:
              path: /health
              port: innovanodejs-port
            initialDelaySeconds: 30
            timeoutSeconds: 40
  selector:
    matchLabels:
      app: myappbackend

       