# Özlem

# 1.  Görevimiz öncelikle önceden oluşturuğumuz pod dosyası ile bir pod oluşturmak için gerekli komutu 
# açıklama satırı şeklinde yazmak
# 2.  Ardından ismi isminizrs1 olan bir replicaset oluşturmak 
# 3.  bu replicaset içerisinde yer alan template için mevcut pod dosyanız içerisindeki bilgileri kullanabilirsiniz
# 4.  replicaset selector bölümüne mathlabel ile innova_app yazalım

# Pod komutu:
   #kubectl create -f Documents/Pods/Özlem_Pod.yaml


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ozlemrs1
  labels:
    app: ozlemaslan
spec:
  replicas: 4
  template:
    metadata:
      name: ozlemaslan
      labels:
        app: innova_app
    spec:
      containers:
        - name: ozlem
          image: httpd
  selector:
    matchLabels:
      app: innova_app
    
