apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendDeploy
  labels:
    environment: frontendDeploy
    tier: frontend
spec:
  replicas: 5
  template:
    metadata:
      name: appfrontend
      labels:
        app: appfrontend
    spec:
      containers:
        - name: frontendCont
          image: nginx
  selector:
    matchLabels:
      app: appfrontend