apiVersion: v1
kind: Pod
metadata:
  name: selamnginx
  labels:
    app: selamnginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config-volume
    - name: nodejsdemo
      image: edizdesign/nodejs-image-demo
      ports:
        - containerPort: 3000
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
          - key: proxy.conf
            path: proxy.conf
