# Özge
#kubectl create -f Özge_Pod.yaml

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ozgers
  labels:
    app: myapprs
spec:
  replicas: 4
  template:
    metadata:
     name: Ozge
     labels:
       app: innova-app
       backend: evet
    spec:   
      containers:
       - name: backend
         image: httpd
  selector:
    matchLabels:
      app: innova-app

