apiVersion: apps/v1
kind: Deployment
metadata:
  name: depsecretornek
  labels:
    app: depSecretOrnek
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depsecpods
  template:
    metadata:
      labels:
        app: depsecpods
    spec:
      containers:
        - name: dep-secret-volumes
          image: nginx
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/creds
              readOnly: true
      volumes: 
        - name: secret-volume
          secret:
            secretName: benimgizlilogin
              
# kubectl exec -i -t depsecret-6884554446-qhsn9 
# -c dep-secret-volumes -- bin/bash