apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentndsscheduled
  labels:
    app: myappdep
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackend
      labels:
        app: myapp
    spec:
      nodeName: minikube # node ismi yazılacak
      containers:
        - name: backend
          image: httpd
  selector:
    matchLabels:
      app: myapp
