# Birbirinden faklı meyvelerin yer aldığı list
# Bilgilerden faydalanarak meyveler ait kalori  ve renk bilgilerini yazalım
Meyveler:
  İsimler:
    - Portakal
    - Elma
    - Karpuz
  Kaloriler:
    - 300
    - 400
    - 200
  Renkler:
    - Turuncu
    - Sarı
    - Kırmızı

Meyve:
  - Portakal
  - Elma
  - Karpuz

Özellikler:
  - Portakal:
    Kalori: 300
    Renk: Turuncu
  - Elma:
    Kalori: 400
    Renk: Sarı
  - Karpuz:
    Kalori: 200
    Renk: Kırmızı        

apiVersion: v1
kind: Pod
metadata:
  name: xxxx
  labels:
    app: ccc
    tier: back
spec:
  containers:
    - name: Containerın ismi #Container İsmi
      image: nginx
    
  