# Talha
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: talhars1
  labels:
    app: myapp_rc
spec:
  replicas: 4
  template:
    metadata:
      name: myappbackend
      labels: 
        app: myapp
        tier: backend
        type: backend
    spec:
      containers:
        - name: backend
          image: httpd
  selector:
    matchLabels:
      app: innovaapp