# Talha
# kubectl apply -f Talha_Pod.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: talhars1
  labels:
    app: innova_app_rs
spec:
  replicas: 4
  template:
    metadata:
      name: talhapod
      labels: 
        app: innova_app
        tier: backend
        type: backend
    spec:
      containers:
        - name: backend
          image: httpd
  selector:
    matchLabels:
      app: innova_app