apiVersion: apps/v1
kind: Deployment
metadata:
  name: banu-dep
  labels:
    app: myappdep-banu
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackend
      labels:
        app: myapp
    spec:
      containers:
        - name: backend
          image: nginx
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: depSecBanusPods
      spec:
        containers:
          name: banu-secret
            image: nginx
            ports:
              name: nginx-port
              containerPort: 80
            volumeMounts:
              name: secret-volume
              mountPath: /etc/creds
              readonly: true
        volumes:
            name: secret-volume
            secret:
              secretName: banu-secret 