#1
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: deployment1
#   labels:
#     app: myappdep
# spec:
#   replicas: 4
#   template:
#     metadata:
#       name: backend
#       labels:
#         app: myapp
#     spec:
#       containers:
#         - name: backend
#           image: nginx
#   selector:
#     matchLabels:
#       app: myapp

#2
#kubectl create -f .\Fatih_deployment.yaml

#3-4
apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  labels:
    app: nodeservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    app: myapp

#kubectl create -f .\nodeservice.yaml 

#5
# kubectl get svc nodeservice


#6
# minikube service nodeservice --url