apiVersion: v1
kind: ReplicationController
metadata:
  name: fatih_rc
  labels:
    app: innova_app
spec:
  replicas: 4
  template:
    metadata:
    name: backend
    labels:
      app: myapp
      tier: backend
    spec:
      containers:
        - name: httpd_container
          image: httpd