apiVersion: v1
kind: Service
metadata:
  name: selamservice
  labels:
    app: selamservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
  selector:
    app: selamnginx


