apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentbackend
  labels:
    app: myappback
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackend
      labels:
        app: myapp
    spec:
      containers:
        - name: backend
          image: ozgeaydiner/hello-world:latest
  selector:
    matchLabels:
      app: myapp
    
