apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentfrontend
  labels:
    app: myappfront
spec:
  replicas: 5
  template:
    metadata:
      name: myappfrontend
      labels:
        app: myapp
    spec:
      containers:
        - name: frontend
          image: httpd
  selector:
    matchLabels:
      app: myapp
    
