apiVersion: v1
kind: Service
metadata:
  name: ServiceNodePort
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: myapp


