#FileName: secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: benimgizlilogin
type: Opaque
data:
  username: aW5ub3ZhCg== # innova
  password: dW54a3ViZXJuZXRlcwo=  # unxkubernetes
  ipAdres: ipadres-innova

#kubectl create -f ./secret.yaml

#FileName: secret_dep.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depsecretornek
  labels:
    app: depSecretOrnek
spec:
  replicas: 3
  selector:
    matchLabels:
      app: depsecpods
  template:
    metadata:
      labels:
        app: depsecpods
    spec:
      containers:
        - name: dep-secret-volumes
          image: nginx
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/creds
              readOnly: true
      volumes: 
        - name: secret-volume
          secret:
            secretName: benimgizlilogin
              
#kubectl create -f ./secret_dep.yaml