apiVersion: v1
kind: ReplicationController
metadata: 
  name: mehmet_rc
  labels:
    app: innova_app
spec:
  replicas: 4
  template:
    metadata:
      name: myappName
      labels: 
        app: myapp
    spec:
      containers:
        - name: backend
          image: httpd
