#1. Daha önce oluşturduğumuz deployment içinde pod içinde container olarak nginx kullandığımızdan emin olalım
#2. deployment dosyasını çalıştırmak için gereken kodu açıklama satırı şeklinde yazalım
#3. bir node port üretelim service kullanarak
#4. bu servisi mevcut deployment'a bağlayalım 
#5. ardından bu servisin liste üzerinden doğrulamasını yapacak kodu yazalım  (kubectl ile)
#6. servisi test edecek kodu yazalım (minikube ile)


#kubectl apply -f mehmet_deployment.yaml

apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: myapp
# kubectl apply -f mehmet_serviceEgsersiz.yaml
# kubectl get svc
# minikube service myappservice

