apiVersion: v1
kind: ReplicationController
metadata: 
  name: mehmet_rc
  labels:
    app: myapp
spec:
  replicas: 4
  template:
    metadata:
      name: backend
      labels: 
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: httpd
