apiVersion: v1
kind: Service
metadata:
  name: Selamservice
spec:
  type: NodePort
  selector:
    app: selamnginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3008
    protocol: TCP
  - port: 81
    targetPort: 3000
    nodePort: 3010
    protocol: TCP
