#1. Birbirinde farklı meyvelerin yer aldığı bir liste oluşturalım
#2. Aşağıdaki bilgilerden faydalanarak meyvelere ait kalori ve renk bilgilerini yazalım (sözlük şeklinde)
#3. Sözlük şeklinde olan bu bilgilerin bir liste halinde tutulmasını sağlayalım 
#isim - kalori - renk
#Portakal - 300 - turuncu
#Elma - 400 - sarı
#Karpuz - 200 - kırmızı
#Tüm egzersizi selam.yaml dosyalarında gerçekleştirebiliriz. 
Meyveler:
  isim:
    - Portakal
    - Elma
    - Karpuz
  renk:
    - Turuncu
    - Sari
    - Kirmizi
  kalori:
    - 300
    - 400
    - 200



#ilk versiyon
apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestApp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: TestApp
  template:
    metadata:
      labels:
        app: TestApp
    spec:
      containers:
      - name: TestApp
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
