apiVersion: apps/v1
kind: Deployment
metadata:
  name: depfront
  labels:
    app: myappdep
spec:
  replicas: 5
  template:
    metadata:
      name: myappfront
      labels:
        app: myapp
        tier: front
    spec:
      containers:
        - name: front
          image: httpd
  selector:
    matchLabels:
      app: myapp
  