apiVersion: apps/v1
kind: Deployment
metadata:
  name: depback
  labels:
    app: myappdep
spec:
  replicas: 5
  template:
    metadata:
      name: myappback
      labels:
        app: myapp
        tier: back
    spec:
      containers:
        - name: back
          image: ozgeaydiner/hello-world:latest
  selector:
    matchLabels:
      app: myapp
    
