apiVersion: v1
kind: Service
metadata:
  name: frontendservice
  labels:
    name: frontendservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
      protocol: TCP
      name: http
  selector:
    app: myappFrontEnd