apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: myappdep
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackend
      labels:
        app: myapp
    spec:
      containers:
        - name: backend
          image: httpd
      resources:
        request:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
  selector:
    matchLabels:
      app: myapp
    
