apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: myappdep
    namespace: benim-namespace
spec:
  replicas: 5
  template:
    metadata:
      name: myappbackend
      labels:
        app: myapp
    spec:
      containers:
        - name: backend
          image: httpd
  selector:
    matchLabels:
      app: myapp
    
