apiVersion: v1
kind: Namespace
metadata:
  name: benim-namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kaynak-quota
  namespace: benim-namespace
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: "100Mi"
    limits.cpu: "200m"
    limits.memory: "200Mi"
--- 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: benim-namespace
spec:
  hard:
    configmaps: "10"
    presistenVolumeClaims: "4"
    secrets: "10"
    services: "10"
    services.nodePorts: "2"
