apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-example
spec:
  limits:
  - default:
       cpu: "200m"
       memory: "200Mi"
    defaultRequest:
        cpu: "100m"
        memory: "100Mi"
    type: Container