# kubectl apply -f /Egzersizler/Tahir/Tahir_pod.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tahirrs1
  labels:
    app: tahirrs1
spec:
  replicas: 5
  template:
    metadata:
      name: innovaapprs
      labels:
        app: innova_app
    spec:
      containers:
        - name: backend
          image: httpd
  selector:
    matchLabels:
      app: innova_app


#kubectl create -f /Egzersizler/Tahir/Tahir_replicaset.yaml