apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-affinity-1
  template:
    metadata:
      labels:
        app: pod-affinity-1
    spec:
      containers:
        - name: podaffdemo
          image: edizdesign/nodejs-image-demo
          ports:
            - name: http-port
              containerPort: 80
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-affinity-2
  template:
    metadata:
      labels:
        app: pod-affinity-2
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - pod-affinity-1
              topologyKey: kubernetes.io/hostname #######################
      containers:
        - name: redis
          image: redis
          ports:
            - name: redis-port
              containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-affinity-3
  template:
    metadata:
      labels:
        app: pod-affinity-3
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - pod-affinity-1
              topologyKey: kubernetes.io/hostname #######################
      containers:
        - name: podaffdemo
          image: edizdesign/nodejs-image-demo
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-affinity-4
  template:
    metadata:
      labels:
        app: pod-affinity-4
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - pod-affinity-1
                    - pod-affinity-3
              topologyKey: kubernetes.io/hostname #######################
      containers:
        - name: podaffdemo
          image: edizdesign/nodejs-image-demo
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-affinity-5
  template:
    metadata:
      labels:
        app: pod-affinity-5
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - pod-affinity-1
                    - pod-affinity-3
              topologyKey: kubernetes.io/hostname #######################
      containers:
        - name: podaffdemo
          image: edizdesign/nodejs-image-demo
          ports:
            - name: http-port
              containerPort: 80